### ISSUE TITLE
Doesn't work in API23

### ISSUE THREAD

**Issue by AppWerft** [appcelerator-archive/ti.barcode#36]
Hello,

I can compile the app (linking of ti.barcode successful), but at runtime comes:

```
02-11 19:01:08.630 24966 24994 E AndroidRuntime: FATAL EXCEPTION: KrollRuntimeThread
02-11 19:01:08.630 24966 24994 E AndroidRuntime: Process: com.eppendorf.appmain, PID: 24966
02-11 19:01:08.630 24966 24994 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.eppendorf.appmain-1/lib/arm/libti.barcode.so: has text relocations
02-11 19:01:08.630 24966 24994 E AndroidRuntime:    at java.lang.Runtime.loadLibrary(Runtime.java:372)
02-11 19:01:08.630 24966 24994 E AndroidRuntime:    at java.lang.System.loadLibrary(System.java:1076)
02-11 19:01:08.630 24966 24994 E AndroidRuntime:    at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
02-11 19:01:08.630 24966 24994 E AndroidRuntime:    at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
02-11 19:01:08.630 24966 24994 E AndroidRuntime:    at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
02-11 19:01:08.630 24966 24994 E AndroidRuntime:    at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)
02-11 19:01:08.632 18536 19224 W ActivityManager:   Force finishing activity com.eppendorf.appmain/.EppendorfActivity
02-11 
```

This issue kills the app.

**Comment by ashcoding** [comment]
May I know what Titanium SDK version you are using and device and which Android version?

**Comment by cjadhav** [comment]
Hi 
I am also facing same issue.
I am using titanium SDK 5.1.2 with API 23 on Nexus 6 (6.0.1)
I am using ti.barcode 2.3.5
On calling "Capture" method the app crashes.

Please please help me to solve the issue.

**Comment by AppWerft** [comment]
Please try to recompile the module with 23

**Comment by cjadhav** [comment]
Hi @AppWerft ,
Thanks for the reply.
Actually there are lot of code base on different forks.
Not getting which repo is fresh and updated for android.
I can see its lastly updated around year ago.

It will be great if you provide me a module or link for the fresh source code.

Thanks you so much for your help.

**Comment by pfwd** [comment]
@AppWerft Still the same issue after recompiling with SDK 23
Tested from the Appcelerator debugger compiling to a Nexus 7 : 
`[ERROR] :  linker: /data/app/com.example.com/lib/arm/libti.barcode.so: has text relocations`

**Comment by AppWerft** [comment]
Fresh code is from @miga http://migaweb.de/ti.barcode-android-2.3.6.zip

**Comment by nascado** [comment]
Did anyone have found a Solution ?
Wie are Looping for a working QR Code Scanner for Android 6.0.1.

**Comment by AppWerft** [comment]
Please look to http://migaweb.de/ti.barcode-android-2.3.6.zip
